# Generated by Django 2.0.3 on 2018-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('video_url', models.CharField(max_length=128)),
                ('price', models.FloatField(default=0)),
                ('image_url', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
